//! Bounded trimming of ordinary memory, with explicit defaults kept whole.

use std::fs;
use std::io::Write;
use std::path::{Component, Path, PathBuf};

use crate::jobs::project_preferences::ProjectPreferencesSnapshot;

use super::{INSTAFY_FILENAME, MAX_INSTAFY_MD_BYTES};

const OVERFLOW_PATH: &str =
    ".agents/skills/instafy-learned/blocks/instafy-memory-overflow/DETAILS.md";

pub(super) fn optimize_instafy_md(
    workspace_dir: &Path,
    changed_paths: &mut Vec<String>,
) -> (usize, usize, Option<&'static str>) {
    let snapshot = ProjectPreferencesSnapshot::load(workspace_dir);
    let source = snapshot.source().unwrap_or_default();
    // A rejected source may still have a known size. Stat without opening or
    // following the leaf so skip diagnostics do not report an oversized file as empty.
    let before = snapshot.source().map(str::len).unwrap_or_else(|| {
        fs::symlink_metadata(workspace_dir.join(INSTAFY_FILENAME))
            .ok()
            .filter(|metadata| metadata.is_file() && !metadata.file_type().is_symlink())
            .map(|metadata| usize::try_from(metadata.len()).unwrap_or(usize::MAX))
            .unwrap_or(0)
    });
    if let Some(reason) = snapshot.unavailable_reason() {
        return (before, before, Some(reason));
    }
    if before <= MAX_INSTAFY_MD_BYTES {
        return (before, before, None);
    }

    let section = snapshot.section().unwrap_or_default();
    let ordinary = snapshot.memory_without_preferences().unwrap_or_default();
    let mut candidate = section.to_owned();
    if !candidate.is_empty() && !candidate.ends_with('\n') {
        candidate.push('\n');
    }
    // A real section boundary prevents the generated notice from becoming a default.
    candidate.push_str(&format!(
        "## Memory overflow\n\n[Truncated by `/learn` optimizer: `{INSTAFY_FILENAME}` exceeded \
         {MAX_INSTAFY_MD_BYTES} bytes. Overflow moved to `{OVERFLOW_PATH}`.]\n\n"
    ));
    let Some(budget) = MAX_INSTAFY_MD_BYTES.checked_sub(candidate.len()) else {
        return (before, before, Some("preferences_exceed_budget"));
    };
    let (prefix, overflow) = split_at_newline_boundary(ordinary, budget);
    candidate.push_str(prefix);
    if !snapshot.preserves_preferences(&candidate) {
        return (before, before, Some("preferences_would_change"));
    }
    let overflow_details = format!(
        "# INSTAFY.md overflow\n\nThis file is generated by the runtime `/learn` optimizer \
         when `{INSTAFY_FILENAME}` grows too large.\n\n## Overflow content\n\n{overflow}"
    );

    match commit_trim(
        workspace_dir,
        source,
        &candidate,
        &overflow_details,
        changed_paths,
    ) {
        Ok(after) => (before, after, None),
        Err(reason) => (before, before, Some(reason)),
    }
}

fn commit_trim(
    workspace_dir: &Path,
    source: &str,
    candidate: &str,
    overflow_details: &str,
    changed_paths: &mut Vec<String>,
) -> Result<usize, &'static str> {
    let root = workspace_dir
        .canonicalize()
        .map_err(|_| "workspace_unavailable")?;
    let (source_file, source_path) = stage_file(&root, INSTAFY_FILENAME, candidate)?;
    let (overflow_file, overflow_path) = stage_file(&root, OVERFLOW_PATH, overflow_details)?;
    if ProjectPreferencesSnapshot::load(&root).source() != Some(source) {
        return Err("source_changed");
    }
    // Never shorten the source unless the removed material was saved successfully.
    overflow_file
        .persist(overflow_path)
        .map_err(|_| "archive_write_failed")?;
    changed_paths.push(OVERFLOW_PATH.to_owned());
    // Check the entire source, not just defaults: an edit or deletion must win.
    if ProjectPreferencesSnapshot::load(&root).source() != Some(source) {
        return Err("source_changed");
    }
    source_file
        .persist(source_path)
        .map_err(|_| "source_write_failed")?;
    changed_paths.push(INSTAFY_FILENAME.to_owned());
    Ok(candidate.len())
}

fn split_at_newline_boundary(text: &str, max_bytes: usize) -> (&str, &str) {
    let mut cut = max_bytes.min(text.len());
    if let Some(pos) = text.as_bytes()[..cut]
        .iter()
        .rposition(|byte| *byte == b'\n')
    {
        cut = pos + 1;
    } else {
        while !text.is_char_boundary(cut) {
            cut -= 1;
        }
    }
    text.split_at(cut)
}

// Only called with the two static paths above. Reject symlinked parent/leaf entries,
// then stage a replacement in the same directory so writes never follow a leaf link.
fn stage_file(
    root: &Path,
    relative: &str,
    content: &str,
) -> Result<(tempfile::NamedTempFile, PathBuf), &'static str> {
    let relative = Path::new(relative);
    let mut parent = root.to_path_buf();
    for component in relative.parent().ok_or("unsafe_destination")?.components() {
        let Component::Normal(component) = component else {
            return Err("unsafe_destination");
        };
        parent.push(component);
        match fs::symlink_metadata(&parent) {
            Ok(metadata) if metadata.is_dir() && !metadata.file_type().is_symlink() => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                fs::create_dir(&parent).map_err(|_| "destination_write_failed")?;
            }
            _ => return Err("unsafe_destination"),
        }
    }
    let destination = root.join(relative);
    let permissions = match fs::symlink_metadata(&destination) {
        Ok(metadata) if metadata.is_file() && !metadata.file_type().is_symlink() => {
            Some(metadata.permissions())
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
        _ => return Err("unsafe_destination"),
    };
    let mut file =
        tempfile::NamedTempFile::new_in(parent).map_err(|_| "destination_write_failed")?;
    file.write_all(content.as_bytes())
        .map_err(|_| "destination_write_failed")?;
    if let Some(permissions) = permissions {
        file.as_file()
            .set_permissions(permissions)
            .map_err(|_| "destination_write_failed")?;
    }
    Ok((file, destination))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn changed_or_deleted_source_is_not_replaced() {
        for current in [Some("New facts; same defaults."), None] {
            let workspace = tempfile::tempdir().unwrap();
            let path = workspace.path().join(INSTAFY_FILENAME);
            if let Some(current) = current {
                fs::write(&path, current).unwrap();
            }
            let mut changed = Vec::new();
            assert_eq!(
                commit_trim(
                    workspace.path(),
                    "Old facts",
                    "Trimmed old facts",
                    "overflow",
                    &mut changed
                ),
                Err("source_changed")
            );
            assert_eq!(fs::read_to_string(path).ok().as_deref(), current);
            assert!(!workspace.path().join(OVERFLOW_PATH).exists());
            assert!(changed.is_empty());
        }
    }
}
