import { createControllerClient } from "@instafy/sdk/controller-client";
import {
  acknowledgeMyNotificationInboxItem,
  addControllerConversationParticipant,
  addControllerOrgMember,
  acquireWorkspaceLease,
  cancelControllerOrgInvitation,
  cancelDeviceAuth,
  clearControllerAccessTokenOverride,
  CONTROLLER_AUTH_ERROR_EVENT,
  CONTROLLER_RUNTIME_IDLE_TTL_SECONDS_DEFAULT,
  CONTROLLER_RUNTIME_IDLE_TTL_SECONDS_MIN,
  coerceControllerRuntimeIdleTtlSeconds,
  controllerBaseUrl,
  controllerJsonRequest,
  clearDefaultCredential,
  readControllerError,
  resolveControllerAccessToken,
  resolveControllerRequestContext,
  createProjectAutomationInController,
  createProjectSecret,
  createBlankControllerConversation,
  createCodexCredential,
  createControllerOrgInvitation,
  createControllerOrgInvitationStrict,
  createControllerOrgInviteLink,
  createControllerOrganization,
  createControllerProject,
  createMyAgent,
  deleteAutomationInController,
  deleteControllerOrganization,
  deleteControllerProject,
  deleteWorkspaceFileFromController,
  deleteMyAgent,
  discoverControllerSkills,
  ensureRuntime,
  fetchConversationMessagesFromController,
  fetchLocalWorkspacePresence,
  fetchOriginSummary,
  fetchProjectConversationsFromController,
  fetchProjectAutomationsFromController,
  fetchRuntimeStatus,
  fetchRunResultFromController,
  fetchRunsFromController,
  fetchWorkspaceGitHistoryFromController,
  fetchWorkspaceGitHistoryReviewFromController,
  fetchWorkspaceGitDiffFromController,
  fetchWorkspaceGitStatusFromController,
  getControllerProjectSummary,
  getControllerProjectSummaryResult,
  getCredentialRequirements,
  getDeviceAuthStatus,
  getWebPushVapidPublicKey,
  getWorkspaceFileRawUrl,
  importGithubProject,
  interruptControllerConversationRuns,
  listMyActivity,
  listMyNotificationInbox,
  markMyActivitySeen,
  listProjectSecrets,
  listWorkspaceEntriesFromController,
  listControllerConversationParticipants,
  listControllerOrgInviteLinks,
  listControllerOrgInvitations,
  listControllerOrgMembers,
  listControllerOrgMembersPage,
  listControllerOrganizations,
  listControllerProjectMembers,
  listControllerProjects,
  listIntegrationProviders,
  listMyAgents,
  listMyCredentials,
  listProjectIntegrations,
  normalizeOriginEndpointForClient,
  readWorkspaceFileFromController,
  recordControllerConversationMessage,
  resolveControllerConversationParticipation,
  releaseWorkspaceLease,
  removeControllerOrgMember,
  removeControllerProjectMember,
  removeMyNativePushToken,
  removeMyWebPushSubscription,
  removeRuntime,
  renewWorkspaceLease,
  requestDesktopRuntime,
  requestOriginAccessToken,
  requestProjectConversationTitle,
  requestProjectEditorInlineCompletion,
  dispatchControllerProviderResourceRead,
  dispatchControllerProviderToolCall,
  heartbeatControllerProviderDevice,
  listControllerProviderDevices,
  listControllerProviderRequests,
  claimControllerProviderRequest,
  completeControllerProviderRequest,
  revertWorkspaceGitCommitFromController,
  revertWorkspaceGitPathsFromController,
  revokeProjectSecret,
  revokeControllerOrgInviteLink,
  revokeMyCredential,
  runAutomationNowInController,
  runtimeControllerEnabled,
  sendControllerConversationMessage,
  setDefaultCredential,
  setRuntimePreference,
  startDeviceAuth,
  startRuntime,
  stopRuntime,
  stopRuntimeIfIdle,
  subscribeToRunsFromController,
  syncWorkspaceGitToRemoteFromController,
  updateControllerOrgInvitationRole,
  testMyCredential,
  updateAutomationInController,
  updateControllerConversationMetadata,
  updateControllerOrgMemberRole,
  updateControllerProjectMemberRole,
  updateControllerProjectName,
  updateProjectSecret,
  updateRuntimeActivity,
  updateMyAgent,
  upsertMyNativePushToken,
  upsertMyWebPushSubscription,
  upsertProjectIntegration,
  writeWorkspaceFileToController,
  applyWorkspaceChangesViaOrigin,
  bootstrapControllerProjectMemory,
  deriveGithubImportTargetPath,
  acceptControllerOrgInvitation,
  previewControllerOrgInvitation,
  getControllerBugReport,
  listControllerBugReports,
  submitControllerBugReport,
  clearSharedBrowserData,
} from "../../services/runtimeController";
import {
  browserSessionStatusIndicatesUnavailable,
  commandRuntimeBrowserSessionPage,
  fetchRuntimeBrowserSessionCapabilities,
  fetchRuntimeBrowserSessionActions,
  fetchRuntimeBrowserSessionPages,
  focusRuntimeBrowserSessionPage,
  isBrowserSessionCapabilitiesIncompatibleError,
  isBrowserSessionUnavailableError,
  mapRuntimeBrowserSessionActionsPayload,
  mapRuntimeBrowserSessionCapabilitiesPayload,
  mapRuntimeBrowserSessionPagesPayload,
} from "../../services/runtimeController/browserSession";
import {
  decideRuntimeSharedBrowserApproval,
  fetchRuntimeSharedBrowserPendingApproval,
  mapRuntimeSharedBrowserPendingApprovalPayload,
} from "../../services/runtimeController/browserApproval";

export const controllerClient = createControllerClient({
  core: Object.freeze({
    get enabled() {
      return runtimeControllerEnabled;
    },
    get baseUrl() {
      return controllerBaseUrl;
    },
    clearAccessTokenOverride: clearControllerAccessTokenOverride,
    runtimeIdleTtlSecondsDefault: CONTROLLER_RUNTIME_IDLE_TTL_SECONDS_DEFAULT,
    runtimeIdleTtlSecondsMin: CONTROLLER_RUNTIME_IDLE_TTL_SECONDS_MIN,
    coerceRuntimeIdleTtlSeconds: coerceControllerRuntimeIdleTtlSeconds,
    resolveAccessToken: resolveControllerAccessToken,
    resolveRequestContext: resolveControllerRequestContext,
    readError: readControllerError,
    authErrorEvent: CONTROLLER_AUTH_ERROR_EVENT,
    jsonRequest: controllerJsonRequest,
    normalizeOriginEndpointForClient,
  }),
  agents: Object.freeze({
    list: listMyAgents,
    create: createMyAgent,
    update: updateMyAgent,
    remove: deleteMyAgent,
  }),
  credentials: Object.freeze({
    list: listMyCredentials,
    createCodex: createCodexCredential,
    revoke: revokeMyCredential,
    clearDefault: clearDefaultCredential,
    setDefault: setDefaultCredential,
    test: testMyCredential,
    getRequirements: getCredentialRequirements,
    startDeviceAuth,
    getDeviceAuthStatus,
    cancelDeviceAuth,
  }),
  projects: Object.freeze({
    create: createControllerProject,
    rename: updateControllerProjectName,
    delete: deleteControllerProject,
    list: listControllerProjects,
    getSummary: getControllerProjectSummary,
    getSummaryResult: getControllerProjectSummaryResult,
    listMembers: listControllerProjectMembers,
    updateMemberRole: updateControllerProjectMemberRole,
    removeMember: removeControllerProjectMember,
    bootstrapMemory: bootstrapControllerProjectMemory,
    importGithub: importGithubProject,
    deriveGithubImportTargetPath,
    // Project-guest invites ARE org invitations carrying a project scope --
    // one storage model, one endpoint family (see org_invitations' nullable
    // project_id). These aliases exist because a developer inviting a guest
    // to a PROJECT should find the verbs under `projects`, not discover by
    // accident that `organizations.createInvitation` is the API for it. Same
    // functions, honestly named at the call site.
    listInvitations: listControllerOrgInvitations,
    createInvitation: createControllerOrgInvitation,
    createInvitationStrict: createControllerOrgInvitationStrict,
    cancelInvitation: cancelControllerOrgInvitation,
    updateInvitationRole: updateControllerOrgInvitationRole,
    listInviteLinks: listControllerOrgInviteLinks,
    createInviteLink: createControllerOrgInviteLink,
    revokeInviteLink: revokeControllerOrgInviteLink,
  }),
  organizations: Object.freeze({
    create: createControllerOrganization,
    delete: deleteControllerOrganization,
    list: listControllerOrganizations,
    listMembers: listControllerOrgMembers,
    listMembersPage: listControllerOrgMembersPage,
    addMember: addControllerOrgMember,
    updateMemberRole: updateControllerOrgMemberRole,
    removeMember: removeControllerOrgMember,
    listInvitations: listControllerOrgInvitations,
    createInvitation: createControllerOrgInvitation,
    createInvitationStrict: createControllerOrgInvitationStrict,
    cancelInvitation: cancelControllerOrgInvitation,
    updateInvitationRole: updateControllerOrgInvitationRole,
    acceptInvitation: acceptControllerOrgInvitation,
    previewInvitation: previewControllerOrgInvitation,
    listInviteLinks: listControllerOrgInviteLinks,
    createInviteLink: createControllerOrgInviteLink,
    revokeInviteLink: revokeControllerOrgInviteLink,
  }),
  conversations: Object.freeze({
    listForProject: fetchProjectConversationsFromController,
    listMessages: fetchConversationMessagesFromController,
    createBlank: createBlankControllerConversation,
    updateMetadata: updateControllerConversationMetadata,
    listParticipants: listControllerConversationParticipants,
    addParticipant: addControllerConversationParticipant,
    recordMessage: recordControllerConversationMessage,
    resolveParticipation: resolveControllerConversationParticipation,
    sendMessage: sendControllerConversationMessage,
    interruptRuns: interruptControllerConversationRuns,
    requestTitle: requestProjectConversationTitle,
  }),
  runtimes: Object.freeze({
    fetchStatus: fetchRuntimeStatus,
    start: startRuntime,
    ensure: ensureRuntime,
    stop: stopRuntime,
    stopIfIdle: stopRuntimeIfIdle,
    remove: removeRuntime,
    requestDesktop: requestDesktopRuntime,
    setPreference: setRuntimePreference,
    updateActivity: updateRuntimeActivity,
  }),
  integrations: Object.freeze({
    listProviders: listIntegrationProviders,
    listForProject: listProjectIntegrations,
    upsert: upsertProjectIntegration,
  }),
  providerRequests: Object.freeze({
    dispatchToolCall: dispatchControllerProviderToolCall,
    dispatchResourceRead: dispatchControllerProviderResourceRead,
    list: listControllerProviderRequests,
    claim: claimControllerProviderRequest,
    complete: completeControllerProviderRequest,
  }),
  providerDevices: Object.freeze({
    list: listControllerProviderDevices,
    heartbeat: heartbeatControllerProviderDevice,
  }),
  workspace: Object.freeze({
    files: Object.freeze({
      list: listWorkspaceEntriesFromController,
      read: readWorkspaceFileFromController,
      write: writeWorkspaceFileToController,
      delete: deleteWorkspaceFileFromController,
      getRawUrl: getWorkspaceFileRawUrl,
    }),
    git: Object.freeze({
      fetchStatus: fetchWorkspaceGitStatusFromController,
      fetchHistory: fetchWorkspaceGitHistoryFromController,
      fetchDiff: fetchWorkspaceGitDiffFromController,
      fetchHistoryReview: fetchWorkspaceGitHistoryReviewFromController,
      syncToRemote: syncWorkspaceGitToRemoteFromController,
      revertPaths: revertWorkspaceGitPathsFromController,
      revertCommit: revertWorkspaceGitCommitFromController,
    }),
    leases: Object.freeze({
      acquire: acquireWorkspaceLease,
      renew: renewWorkspaceLease,
      release: releaseWorkspaceLease,
    }),
    origin: Object.freeze({
      fetchLocalPresence: fetchLocalWorkspacePresence,
      fetchSummary: fetchOriginSummary,
      requestAccessToken: requestOriginAccessToken,
      applyChanges: applyWorkspaceChangesViaOrigin,
    }),
  }),
  activity: Object.freeze({
    list: listMyActivity,
    markSeen: markMyActivitySeen,
  }),
  notifications: Object.freeze({
    getWebPushVapidPublicKey,
    upsertWebPushSubscription: upsertMyWebPushSubscription,
    removeWebPushSubscription: removeMyWebPushSubscription,
    upsertNativePushToken: upsertMyNativePushToken,
    removeNativePushToken: removeMyNativePushToken,
    listInbox: listMyNotificationInbox,
    acknowledgeInboxItem: acknowledgeMyNotificationInboxItem,
  }),
  automations: Object.freeze({
    listForProject: fetchProjectAutomationsFromController,
    create: createProjectAutomationInController,
    update: updateAutomationInController,
    delete: deleteAutomationInController,
    runNow: runAutomationNowInController,
  }),
  skills: Object.freeze({
    discover: discoverControllerSkills,
  }),
  secrets: Object.freeze({
    listForProject: listProjectSecrets,
    createForProject: createProjectSecret,
    updateForProject: updateProjectSecret,
    revokeForProject: revokeProjectSecret,
  }),
  runs: Object.freeze({
    fetchResult: fetchRunResultFromController,
    fetch: fetchRunsFromController,
    subscribe: subscribeToRunsFromController,
  }),
  browserSessions: Object.freeze({
    fetchCapabilities: fetchRuntimeBrowserSessionCapabilities,
    fetchPages: fetchRuntimeBrowserSessionPages,
    fetchActions: fetchRuntimeBrowserSessionActions,
    focusPage: focusRuntimeBrowserSessionPage,
    commandPage: commandRuntimeBrowserSessionPage,
    fetchPendingApproval: fetchRuntimeSharedBrowserPendingApproval,
    decideApproval: decideRuntimeSharedBrowserApproval,
    mapCapabilitiesPayload: mapRuntimeBrowserSessionCapabilitiesPayload,
    mapPagesPayload: mapRuntimeBrowserSessionPagesPayload,
    mapActionsPayload: mapRuntimeBrowserSessionActionsPayload,
    mapPendingApprovalPayload: mapRuntimeSharedBrowserPendingApprovalPayload,
    statusIndicatesUnavailable: browserSessionStatusIndicatesUnavailable,
    isCapabilitiesIncompatibleError: isBrowserSessionCapabilitiesIncompatibleError,
    isUnavailableError: isBrowserSessionUnavailableError,
  }),
  browserProfiles: Object.freeze({
    clearForProject: clearSharedBrowserData,
  }),
  completions: Object.freeze({
    requestProjectEditorInline: requestProjectEditorInlineCompletion,
  }),
  bugReports: Object.freeze({
    submit: submitControllerBugReport,
    list: listControllerBugReports,
    get: getControllerBugReport,
  }),
});
