launch=gpgsql
gpgsql-host=postgres
gpgsql-port=5432
gpgsql-dbname=tunnel_broker
gpgsql-user=tunnel_broker
gpgsql-password=password
gpgsql-dnssec=no
local-address=0.0.0.0
local-port=53
disable-axfr=yes
setuid=pdns
setgid=pdns
loglevel=4
version-string=anonymous
guardian=yes
webserver=yes
api=yes
api-key=dev-pdns-key
webserver-address=0.0.0.0
webserver-port=8081
webserver-allow-from=0.0.0.0/0,::/0
