export {
  SPEECH_BOOTSTRAP_HOST_DEPENDENCIES_TOOL_ID,
  SPEECH_HOST_DEPENDENCY_STATUS_RESOURCE_URI,
  SPEECH_PROVIDER_ID,
  SPEECH_PROVIDER_TITLE,
  SPEECH_PROVIDER_TYPE,
  SPEECH_STATUS_RESOURCE_URI,
  SPEECH_SYNTHESIS_CAPABILITY_ID,
  SPEECH_SYNTHESIZE_SPEECH_TOOL_ID,
  SPEECH_TRANSCRIBE_AUDIO_TOOL_ID,
  SPEECH_TRANSCRIPTION_CAPABILITY_ID,
  SPEECH_VOICES_RESOURCE_URI,
} from "@instafy/provider-contract/builtins";
